name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' # Update with the version you're using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal --configuration Release

    - name: Collect Code Coverage
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Report Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: $(Agent.TempDirectory)/TestResults/**/*.xml
